# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 16:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('website', models.URLField()),
                ('created_on', models.DateTimeField(default=datetime.datetime(2016, 10, 6, 16, 30, 5, 666873, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='PurchasedAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20)),
                ('newspaper', models.CharField(max_length=100)),
                ('cost', models.CommaSeparatedIntegerField(max_length=10)),
                ('objective', models.TextField()),
                ('ad_date', models.DateField()),
                ('created_on', models.DateTimeField(default=datetime.datetime(2016, 10, 6, 16, 30, 5, 744424, tzinfo=utc))),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.Brand')),
            ],
        ),
    ]
