# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 16:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_auto_20161006_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 6, 16, 36, 22, 490723, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='purchasedad',
            name='cost',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='purchasedad',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 6, 16, 36, 22, 527745, tzinfo=utc)),
        ),
    ]
