# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 18:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_auto_20161006_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newspaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2016, 10, 6, 18, 4, 7, 691086, tzinfo=utc))),
            ],
        ),
        migrations.RemoveField(
            model_name='purchasedad',
            name='size',
        ),
        migrations.AddField(
            model_name='purchasedad',
            name='package',
            field=models.CharField(default='NULL', max_length=350),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brand',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 6, 18, 4, 7, 655062, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='purchasedad',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 6, 18, 4, 7, 692087, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='purchasedad',
            name='newspaper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.Newspaper'),
        ),
    ]
