# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 18:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_auto_20161006_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 6, 18, 28, 24, 158440, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 6, 18, 28, 24, 216478, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='purchasedad',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 6, 18, 28, 24, 217479, tzinfo=utc)),
        ),
    ]
